let basicQuestions = {
        "Attribute": "A key-value pair in an HTML element. You can use HTML attributes to control certain aspects of an element, like where the element links to or the size of the element.",
        "Array": "A list of JavaScript values. In an array, each value has an index, which is the numbered position of that value in the array. The first value is at index 0, the next value is at index 1, and so on.",
        "Boolean": "A value that can be either true or false.",
        "Camel Case": "A common way to name variables in which you capitalize the first letter of each word (except for the first word) and then join all the words to make one long word.",
        "'DOM' Stands For": "Document Object Model",
        "What is the DOM": "The way that web browsers organize and keep track of HTML elements on a web page. These elements are organized in a treelike structure called the DOM tree. JavaScript and jQuery provide methods that work with the DOM to create and modify elements.",
        "Index": "A number that indicates the position of a value inside an array. The index can be used to access a specific value in an array.",
        "Key-Value Pair": "A pair made up of a string (called a key) that is matched with a particular value (which can be any type of value). They go inside JavaScript objects, and they are used to define an object's properties and methods.",
        "Library": "A collection of JavaScript code that we can load into our web pages to provides additional functions and method. In this book we use the jQuery library, which gives us functions and methods for working with the DOM more easily.",
        "Object": "A set of key-value pairs. Each key is a string that can be paired with any JavaScript value. You can then use the key to retrieve whatever value it's paired with in the object.",
        "String": "A list of characters surrounded by quotes, used to represent text in computer programs.",
        "Syntax": "How keywords, punctuation, and other characters are combined to make working JavaScript programs.",
        "Variable": "A way to give a JavaScript value a name. After you assign a value to a variable, you can use the variable name later to retrieve the value.",
        "For Loop": "The most common way to create a loop in JavaScript",
        "While Loop": "Sets up conditions under which aloop executes",
        "Do while Loop": "Similar to the while loop, however, it executes at least once and performs a check at the end to see if the condition is met to execute again",
        "Break Loop": "Used to stop and exit the cycle at certain conditions",
        "Continue Loop": "Skip parts of the cycle if certain conditions are met",
    }